### ISSUE TITLE
🚧 Error de selectores

### ISSUE THREAD

**Issue by d4lion** [jonathanG29/Amadeus#5]
### 🌏 Descripción 
Durante una carga del DOM hay elementos que aun no existen y estan siendo seleccionados o el dom aun no se a cargado lo que daña el posible uso de la API de document del navegador

![image](https://github.com/user-attachments/assets/4cdaa2ee-2241-446b-9fbf-2b8fc59f7609)

### 🧠 ¿Por qué hacer el cambio, si igual funciona?
Debido a que el proyecto al ser finalizado debe compilarse si se desea hacer un deploy del mismo, debemos tener en cuenta que esta seleccion afecta este despligue, en servicios como vercel, netlify, etc... esto se puede evidenciar [aquí](https://github.com/d4lion/Reto-Amadeus-Grupo-1/pull/1) en donde el intento de hacer deploy solo nos genera errores porque el DOM aun no existe dentro del contexto.

![image](https://github.com/user-attachments/assets/191fbc93-0b3e-477e-b4ae-c223c4a575df)

### ➕ UI Error
Tambien dentro de la UI se rompen algunas cosas por la carga no controlada de los elementos lo cual ocasiona que se vean imagenes adicionales o no esperadas, lo cual podria dañar la experiencia del usuario.

![image](https://github.com/user-attachments/assets/dac61049-17c4-4d3c-8e94-0606dc362b42)

**Comment by d4lion** [comment]
La solución dada para este problema puede ser vista en la PR #6 donde se define de manera explicita la manera en la cual esta puede ser soucionada.

**Comment by jonathanG29** [comment]
se hace merge y se cierra issue
